config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first -> highest priority

  # Changes root page to the home page
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  # Created:
    # A new article path
    # A post to create articles
    # An edit article path
    # A patch to update articles
    # Delete article path
    # Show article path
    # Index article path

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # Sets login to sessions/new page
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Created crud paths for categories
  resources :categories

end

app/models/article.rb
class Article < ApplicationRecord
  # Creates associations: this class gives us getters and setters for
  # each column in the table we created with migrate
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  # Require following validations to save
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # Calls methods on certain pages
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # Important to have these actions in order

  def new
    # Creates a new instance of Article
    @article = Article.new
  end

  def edit
  end

  def index
    # Finds all articles and paginates them
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def create
    # Creates new article given article parameters
    @article = Article.new(article_params)
    @article.user = current_user
    # Conventional syntax
    if @article.save
      flash[:success] = "Article was succefully created"
      redirect_to article_path(@article)
    else
      render 'new' # or :new
    end
  end

  def update
    # Updates article given article parameters
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    # Deletes instance of article
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  # All methods under 'private' can only be called implicitly in controller
  private
    # Sets instance of an article with certain params
    def set_article
      @article = Article.find(params[:id])
    end

    # Sets params with requirements for articles
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    # True if loggin in user is the same as user who wrote article or admin
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/views/articles/_article.html.erb
<%# Partial called in article index  %>
<%# obj set in render call %>
<% obj.each do |article| %>
  <!-- Containers for content in div's -->
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <!-- link_to "Link name", link path -->
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%# Shortens description to 100 words if over %>
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <!-- Displays time in words for article attributes -->
            <small>Created: <%= time_ago_in_words(article.created_at) %> ago |
                   Updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <!-- If the article is associated with categories, display them -->
        <% if article.categories.any? %>
          <p><%= render article.categories %></p>
        <% end %>
        <%# Article actions only displayed if user logged in is %>
        <%# associated with article or is admin %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article",   edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%# Delete action has a confirmation request %>
            <%= link_to "Delete this article", article_path(article),
                                               method: :delete,
                                               data: {confirm: "Are you sure you want to delete this article?"},
                                               class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%# Partial used in article edit and new %>
<%= render 'shared/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    <%# Add the "form-horizontal" form to articles %>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2 col-sm-offset-1">
          <!-- form_for methods to create label -->
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%# form_for methods to create input field %>
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2 col-sm-offset-1">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%# Input field with custom display %>
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-3 col-sm-8">
            <%# form_for methods to create checkboxes for each category %>
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%# Defines checkbox layout for each category %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">
          <!-- form_for methods to create submit button and submit inputs -->
          <%= f.submit class: 'btn btn-primary btn-lg', id: "form_label" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-3">
      <%= link_to "Cancel request and return to articles", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 id="title">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 id="title">Articles</h1>
<div align="center">
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%# Creates pagination below article index %>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 id="title">Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 id="title"><%= @article.title %></h2>
<div class="container-fluid">
  <div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by</li>
            <!-- Displays gravatar image and links to user page -->
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%# Username displayed also links to user page %>
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
          </div>
        </div>
      </ul>
    <% end %>
    <%# simple_format returns pre-editted html format for argument %>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
      <%# Shortcut to list all categories without itterating %>
      <p><%= render @article.categories %></p>
    <% end %>
    <!-- Only display article actions if loggin in associated -->
    <!-- with article of admin -->
    <div class="article-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit this article",    edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article",  article_path(@article),
                                            method: :delete,
                                            data: {confirm: "Are you sure you want to delete this article?"},
                                            class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "View all Articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
  </div>
</div>