config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first -> highest priority

  # Changes root page to the home page
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  # Created:
    # A new article path
    # A post to create articles
    # An edit article path
    # A patch to update articles
    # Delete article path
    # Show article path
    # Index article path

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # Sets login to sessions/new page
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Created crud paths for categories
  resources :categories

end

app/models/category.rb
class Category < ApplicationRecord
  # Comment info in article model
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # Similar method commented info in articles_controller
  before_action :set_category, only: [:edit, :update, :show, :destroy]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:danger] = "Category was successfully deleted"
    redirect_to categories_path
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  # True if not logged in or user is not admin
  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<!-- Category tags under article view -->
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%# Partial used in article edit and new %>
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2 col-sm-offset-1">
      <%= f.label :name %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>
<div class="col-xs-4 col-xs-offset-3">
  <%= link_to "Cancel request and return to categories", categories_path %>
</div>

app/views/categories/edit.html.erb
<h1 id="title">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<!-- List all categories -->
<h1 id="title">Categories</h1>
<div align="center">
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name.capitalize}", category_path(category) %>
          </li>
          <li><small><%= pluralize(category.articles.count, "article") %></small></li>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Delete Category",  category_path(category),
                                                method: :delete,
                                                data: {confirm: "Are you sure you want to delete this category?"},
                                                class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 id="title">Create Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 id="title"><%= @category.name.capitalize + " Articles" %></h1>
<div align="center">
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
      <%= link_to "Delete Category",  category_path(@category),
                                          method: :delete,
                                          data: {confirm: "Are you sure you want to delete this category?"},
                                          class: "btn btn-xs btn-danger" %>
      <br><br>
    </div>
  <% end %>
  <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles %>
</div>