config/routes.rb
Rails.application.routes.draw do
  # Priority is based on order of creation: first -> highest priority

  # Changes root page to the home page
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  # Created:
    # A new article path
    # A post to create articles
    # An edit article path
    # A patch to update articles
    # Delete article path
    # Show article path
    # Index article path

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  # Sets login to sessions/new page
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # Created crud paths for categories
  resources :categories

end

app/views/layouts/_footer.html.erb
<!-- Footer displayed on the obttom of each page -->
<div>
  <footer class="footer">
    <!-- &copy diplays copywrite symbol -->
    <small>
      Copyright &copy; not made by SquareSpace
      <br>
      was made by <%= link_to "Marc", User.find_by(username: "Marc") %>
    </small>
    <nav>
      <ul>
        <li><small><%= link_to "About", about_path %></small></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<!-- Displays any flash messages -->
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <!-- &#215; displays 'X' to close -->
        <a herf="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navbar displayed on the top of each page -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <!-- Styling for symbol when collpased -->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Logo on the left of the navbar -->
      <%= link_to "A B", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Bloggers", users_path %></li>
        <li class="dropdown">
          <!-- Allows for dropbar to toggle -->
          <a href="#" class="dropdown-toggle"class="dropdown-toggle" data-toggle="dropdown"
                      role="button" aria-haspopup="true"
                      aria-expanded="false">Categories<span class="caret"></span></a>
          <!-- Contents under dropdwn menu -->
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <%# Sperator between menu items %>
              <li role="seperator" class="divider"></li>
              <li><%= link_to "New Category", new_category_path %>
            <% end %>
          </ul>
        </li>
      </ul>
      <!-- Search bar on left (not functional) -->
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" />
        </div>
        <!-- Search button -->
        <!-- <button type="submit" class="btn btn-default">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </button> -->
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <!-- Dropdown menu when user is loggged in -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                          role="button" aria-haspopup="true"
                          aria-expanded="false">
                          <%= gravatar_for current_user, size: 19 %>
                          <%= current_user.username %>
                          <%= "Admin" if current_user.admin? %>
                          <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
                <li><%= link_to "New article", new_article_path %></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
          <%# Links when user is not logged in %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!-- Wrapper for all html.erb files -->
<!DOCTYPE html>
<html lang="en-US">
<html>
  <!-- Info for app in head -->
  <head>
    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Link to google fonts for Just Another Hand, Acme and Open Sans -->
    <link href="https://fonts.googleapis.com/css?family=Just+Another+Hand|Acme|Open+Sans" rel="stylesheet">
    <%= favicon_link_tag asset_path('icon.png') %>
    <%# Links to stylesheets and javascript files %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# Renders navigation bar %>
    <%= render 'layouts/navigation' %>
    <%# Renders any flash messages %>
    <%= render 'layouts/messages' %>
    <%# Renders content of web page %>
    <%= yield %>
    <%# Renders footer %>
    <%= render 'layouts/footer' %>
    <br><br>
    <%# Renders debug information in deveopment only %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>